CREATE OR REPLACE PROCEDURE CLARITY_ADMIN.PENDING_OSS_PE_TASKS_DATA AS


CURSOR GET_BASE_DATA IS
        SELECT
            PE_NUMBER, 
            PE_STATUS,
            PE_NATURE,
            PE_TYPE,
            PE_TITLE, 
            AREA, 
            WO_ID,
            WO_TASKNAME, 
            WORKGROUP, 
            WO_STATUS,
            WO_ASSIGN_DATE, 
            SO_ID,
            WOOC_USERID             AS "COMMENT_USER",
            WOOC_TIMESTAMP          AS "COMMENT_DATE",
            WOOC_TEXT               AS "COMMENTS"

            FROM
            (
            SELECT
            PLAE_NUMBER                 AS "PE_NUMBER", 
            PLAE_STATE                  AS "PE_STATUS",
            PLAE_CREATEDCENTER          AS "PE_NATURE",
            PLAE_ACTT_ABBREVIATION      AS "PE_TYPE",
            SUBSTR (PLAE_TITLE,1,12)    AS "PE_TITLE",
            PLAE_REQA_ABBREVIATION      AS "AREA",
            SERO_ID                     AS "SO_ID", 
            WORO_ID                     AS "WO_ID",
            WORO_TASKNAME               AS "WO_TASKNAME", 
            WORO_WORG_NAME              AS "WORKGROUP", 
            WORO_STAS_ABBREVIATION      AS "WO_STATUS",
            WORO_DATECREATED            AS "WO_ASSIGN_DATE", 
            (SELECT MAX(WOOC_TIMESTAMP) FROM WORK_ORDER_COMMENTS WHERE WOOC_WORO_ID = WORO_ID ) AS LNK

            FROM
            SERVICE_ORDERS,
            PLANNED_EVENTS,
            WORK_ORDER,
            SERVICE_IMPLEMENTATION_TASKS

            WHERE
                SERO_OEID   = PLAE_NUMBER
            AND SERO_ID     = WORO_SERO_ID
            AND WORO_STAS_ABBREVIATION IN ('INPROGRESS','ASSIGNED')
            AND SERO_SERT_ABBREVIATION = 'PLANNED_EVENTS'
            AND SEIT_STAS_ABBREVIATION = 'INPROGRESS'
            AND SEIT_WORG_NAME = 'CEN-ENG-OSS'
            AND SERO_ID   = SEIT_SERO_ID
            AND SEIT_TASKNAME IN ('UPLOAD STATIC OSS','BLOCK OLD LOCATIONS','CHANGE PORT STATUS','CHANGE PORT-STATUS','UPDATE OSS')
            ) A,
            WORK_ORDER_COMMENTS

            WHERE 
                WO_ID = WOOC_WORO_ID(+)
            AND LNK = WOOC_TIMESTAMP(+);


GET_BASE_DATA_REC             GET_BASE_DATA%ROWTYPE;

BEGIN

DELETE FROM CLARITY_ADMIN.PENDING_OSS_PE_TASKS;

OPEN GET_BASE_DATA;

LOOP 

FETCH GET_BASE_DATA INTO GET_BASE_DATA_REC ;

EXIT WHEN GET_BASE_DATA%NOTFOUND;

INSERT INTO CLARITY_ADMIN.PENDING_OSS_PE_TASKS
(
PE_NUMBER,
PE_STATUS,
PE_NATURE,
PE_TYPE,
PE_TITLE,
AREA,
WO_ID,
WO_TASKNAME,
WORKGROUP,
WO_STATUS,
WO_ASSIGN_DATE,
SO_ID,
COMMENT_USER,
COMMENT_DATE,
COMMENTS
)
VALUES
(
GET_BASE_DATA_REC.PE_NUMBER,
GET_BASE_DATA_REC.PE_STATUS,
GET_BASE_DATA_REC.PE_NATURE,
GET_BASE_DATA_REC.PE_TYPE,
GET_BASE_DATA_REC.PE_TITLE,
GET_BASE_DATA_REC.AREA,
GET_BASE_DATA_REC.WO_ID,
GET_BASE_DATA_REC.WO_TASKNAME,
GET_BASE_DATA_REC.WORKGROUP,
GET_BASE_DATA_REC.WO_STATUS,
GET_BASE_DATA_REC.WO_ASSIGN_DATE,
GET_BASE_DATA_REC.SO_ID,
GET_BASE_DATA_REC.COMMENT_USER,
GET_BASE_DATA_REC.COMMENT_DATE,
GET_BASE_DATA_REC.COMMENTS
);

END LOOP;

CLOSE GET_BASE_DATA;

COMMIT;

END PENDING_OSS_PE_TASKS_DATA;

---- Sasith 21-02-2014 -----
/
