CREATE OR REPLACE PROCEDURE CLARITY_ADMIN.PENDING_ENTERPRICE_DATA IS

CURSOR GET_SO_PENDING_DATA IS 
SELECT
XX.SERO_ID,
XX.SERO_SERT_ABBREVIATION,
XX.SERO_ORDT_TYPE,
XX.SERO_DATECREATED,
XX.SERO_COMPLETION_DATE,
XX.DELAY_OF_SERVICE_REQUIRED_DATE,
XX.SERO_STAS_ABBREVIATION,
XX.SERO_ACCT_NUMBER,
XX.SERO_CUSR_ABBREVIATION,
XX.SERO_CIRT_NAME,
XX.SERO_SEOP_PRIORITY,
XX.OVERALL_SO_DURATION,
XX.WORO_TASKNAME,
XX.SEIT_WORG_NAME,
XX.SEIT_PROPOSED_START_DATE,
XX.SEIT_STAS_ABBREVIATION,
XX.PENDING_WO_TIME,
XX.WOOA_ACTIVITYNAME,
XX.WOOA_WORG_NAME,
XX.WO_ACTIVITY_TIME,
XX.WOOA_STAS_ABBREVIATION,
MAX_DATE,
WOOC_TEXT

FROM
(
SELECT 
SERO_ID,
SERO_SERT_ABBREVIATION,
SERO_ORDT_TYPE,
SERO_DATECREATED,
SERO_COMPLETION_DATE,
ROUND(SYSDATE - SERO_COMPLETION_DATE) AS "DELAY_OF_SERVICE_REQUIRED_DATE",
SERO_STAS_ABBREVIATION,
SERO_ACCT_NUMBER,
SERO_CUSR_ABBREVIATION,
SERO_CIRT_NAME,
SERO_SEOP_PRIORITY,
ROUND(SYSDATE - SERO_DATECREATED) AS "OVERALL_SO_DURATION",
WORO_TASKNAME,
SEIT_WORG_NAME,
SEIT_PROPOSED_START_DATE,
SEIT_STAS_ABBREVIATION,
ROUND(SYSDATE - SEIT_ACTUAL_START_DATE) AS "PENDING_WO_TIME",
WORO_ID,
WOOA_ACTIVITYNAME,
WOOA_WORG_NAME,
ROUND(SYSDATE - WOOA_ASSIGNED) AS "WO_ACTIVITY_TIME",
WOOA_STAS_ABBREVIATION,
(SELECT MAX(WOOC_TIMESTAMP)FROM  WORK_ORDER_COMMENTS WHERE WORO_ID = WOOC_WORO_ID ) AS MAX_DATE

FROM 
SERVICE_ORDERS,
SERVICE_IMPLEMENTATION_TASKS,
WORK_ORDER,
WORK_ORDER_ACTIVITIES
WHERE 
    SERO_SERT_ABBREVIATION  LIKE ('D-%')
AND SERO_STAS_ABBREVIATION  IN ('PROPOSED','APPROVED')
AND SERO_ID                 = SEIT_SERO_ID
AND SEIT_STAS_ABBREVIATION  ='INPROGRESS' 
AND SEIT_ID = WORO_SEIT_ID
AND WORO_ID = WOOA_WORO_ID(+)
) XX,
WORK_ORDER_COMMENTS
WHERE
    WORO_ID = WOOC_WORO_ID(+)
AND MAX_DATE = WOOC_TIMESTAMP(+) ;


CURSOR GET_CIRT_NAME IS
SELECT 
SO_ID,
CIRT_DISPLAYNAME
FROM 
CLARITY_ADMIN.PENDING_ETHERNET_DATA,
CIRCUITS
WHERE 
    SO_CIRT_NAME   = CIRT_NAME(+);


CURSOR GET_CUST_INFO  IS
SELECT
SO_ID,
CUSR_NAME,CUSR_CUTP_TYPE
FROM
CLARITY_ADMIN.PENDING_ETHERNET_DATA,
CUSTOMER
WHERE 
    CUST_CR         = CUSR_ABBREVIATION
AND CUSR_NAME NOT LIKE 'OSS%';


CURSOR GET_SERVICE_CATEGORY  IS
SELECT 
SO_ID,
SEOA_DEFAULTVALUE
FROM 
CLARITY_ADMIN.PENDING_ETHERNET_DATA,
SERVICE_ORDER_ATTRIBUTES
WHERE 
    SO_ID  = SEOA_SERO_ID(+)
AND SEOA_NAME   ='SERVICE CATEGORY' ;


CURSOR GET_SECTION_HANDLED_BY  IS
SELECT 
SO_ID,
SEOA_DEFAULTVALUE
FROM 
CLARITY_ADMIN.PENDING_ETHERNET_DATA,
SERVICE_ORDER_ATTRIBUTES
WHERE 
    SO_ID  = SEOA_SERO_ID(+)
AND SEOA_NAME   ='SECTION HANDLED BY' ;


CURSOR GET_ACCESS_MEDIUM  IS
SELECT 
SO_ID,
SEOA_DEFAULTVALUE
FROM 
CLARITY_ADMIN.PENDING_ETHERNET_DATA,
SERVICE_ORDER_ATTRIBUTES
WHERE 
    SO_ID  = SEOA_SERO_ID(+)
AND SEOA_NAME   ='ACCESS MEDIUM' ;


CURSOR GET_SERVICE_SPEED  IS
SELECT 
SO_ID,
SEOA_DEFAULTVALUE
FROM 
CLARITY_ADMIN.PENDING_ETHERNET_DATA,
SERVICE_ORDER_ATTRIBUTES
WHERE 
    SO_ID  = SEOA_SERO_ID(+)
AND SEOA_NAME   ='SERVICE_SPEED' ;


CURSOR GET_ACCM_NAME  IS
SELECT
SO_ID,
ACCM_NAME
FROM
CLARITY_ADMIN.PENDING_ETHERNET_DATA,
ACCOUNTS,ACCOUNT_MANAGERS
WHERE 
    CUST_ACCOUNT = ACCT_NUMBER
AND ACCT_ACCM_ID = ACCM_ID(+);
    
GET_SO_PENDING_DATA_REC     GET_SO_PENDING_DATA%ROWTYPE;
GET_CIRT_NAME_REC           GET_CIRT_NAME%ROWTYPE;
GET_CUST_INFO_REC           GET_CUST_INFO%ROWTYPE;
GET_SERVICE_CATEGORY_REC    GET_SERVICE_CATEGORY%ROWTYPE;
GET_SECTION_HANDLED_BY_REC  GET_SECTION_HANDLED_BY%ROWTYPE;
GET_ACCESS_MEDIUM_REC       GET_ACCESS_MEDIUM%ROWTYPE;
GET_SERVICE_SPEED_REC       GET_SERVICE_SPEED%ROWTYPE;
GET_ACCM_NAME_REC           GET_ACCM_NAME%ROWTYPE;



BEGIN

DELETE FROM CLARITY_ADMIN.PENDING_ETHERNET_DATA WHERE SO_ID IS NOT NULL;

OPEN GET_SO_PENDING_DATA;

LOOP 

FETCH GET_SO_PENDING_DATA INTO GET_SO_PENDING_DATA_REC ;

EXIT WHEN GET_SO_PENDING_DATA%NOTFOUND;

INSERT INTO CLARITY_ADMIN.PENDING_ETHERNET_DATA
(
SO_ID,
SERVICE_TYPE,
ORDER_TYPE,
SO_DATE_CREATED,
SERVICE_REQUIRED_DATE,
DELAY_OF_SERVICE_REQUIRED_DATE,
SO_STATUS,
CUST_ACCOUNT,
CUST_CR,
SO_CIRT_NAME,
SERVICE_PRIORITY,
OVERALL_SO_AGE,
INPROGRESS_TASK, 
TASK_WG,
ACTUAL_START_DATE,
TASK_STATUS,
PENDING_WO_DURATION,
WO_ACTIVITY_NAME,
WO_ACTIVITY_WG,
WO_ACTIVITY_DURATION,
WO_ACTIVITY_STATUS,
WO_TIMESTAMP,
WO_COMMENT
)
VALUES
(
GET_SO_PENDING_DATA_REC.SERO_ID,
GET_SO_PENDING_DATA_REC.SERO_SERT_ABBREVIATION,
GET_SO_PENDING_DATA_REC.SERO_ORDT_TYPE,
GET_SO_PENDING_DATA_REC.SERO_DATECREATED,
GET_SO_PENDING_DATA_REC.SERO_COMPLETION_DATE,
GET_SO_PENDING_DATA_REC.DELAY_OF_SERVICE_REQUIRED_DATE,
GET_SO_PENDING_DATA_REC.SERO_STAS_ABBREVIATION,
GET_SO_PENDING_DATA_REC.SERO_ACCT_NUMBER,
GET_SO_PENDING_DATA_REC.SERO_CUSR_ABBREVIATION,
GET_SO_PENDING_DATA_REC.SERO_CIRT_NAME,
GET_SO_PENDING_DATA_REC.SERO_SEOP_PRIORITY,
GET_SO_PENDING_DATA_REC.OVERALL_SO_DURATION,
GET_SO_PENDING_DATA_REC.WORO_TASKNAME,
GET_SO_PENDING_DATA_REC.SEIT_WORG_NAME,
GET_SO_PENDING_DATA_REC.SEIT_PROPOSED_START_DATE,
GET_SO_PENDING_DATA_REC.SEIT_STAS_ABBREVIATION,
GET_SO_PENDING_DATA_REC.PENDING_WO_TIME,
GET_SO_PENDING_DATA_REC.WOOA_ACTIVITYNAME,
GET_SO_PENDING_DATA_REC.WOOA_WORG_NAME,
GET_SO_PENDING_DATA_REC.WO_ACTIVITY_TIME,
GET_SO_PENDING_DATA_REC.WOOA_STAS_ABBREVIATION,
GET_SO_PENDING_DATA_REC.MAX_DATE,
GET_SO_PENDING_DATA_REC.WOOC_TEXT
); 

END LOOP;

CLOSE GET_SO_PENDING_DATA;

COMMIT;
-------------------------------------------------

OPEN GET_CIRT_NAME;

LOOP 

FETCH GET_CIRT_NAME INTO GET_CIRT_NAME_REC ;

EXIT WHEN GET_CIRT_NAME%NOTFOUND;

UPDATE 
    CLARITY_ADMIN.PENDING_ETHERNET_DATA SET DATA_CCT = GET_CIRT_NAME_REC.CIRT_DISPLAYNAME 
WHERE SO_ID = GET_CIRT_NAME_REC.SO_ID ;


END LOOP;

CLOSE GET_CIRT_NAME;

------------------------------------------------

OPEN GET_CUST_INFO;

LOOP 

FETCH GET_CUST_INFO INTO GET_CUST_INFO_REC ;

EXIT WHEN GET_CUST_INFO%NOTFOUND;

UPDATE 
    CLARITY_ADMIN.PENDING_ETHERNET_DATA  SET 

CUSTOMER_NAME    = GET_CUST_INFO_REC.CUSR_NAME,
CUSTOMER_TYPE    = GET_CUST_INFO_REC.CUSR_CUTP_TYPE

WHERE SO_ID = GET_CUST_INFO_REC.SO_ID ;


END LOOP;

CLOSE GET_CUST_INFO;

-------------------------------------------------

OPEN GET_SERVICE_CATEGORY;

LOOP 

FETCH GET_SERVICE_CATEGORY INTO GET_SERVICE_CATEGORY_REC ;

EXIT WHEN GET_SERVICE_CATEGORY%NOTFOUND;

UPDATE 
    CLARITY_ADMIN.PENDING_ETHERNET_DATA SET SERVICE_CATEGORY  = GET_SERVICE_CATEGORY_REC.SEOA_DEFAULTVALUE 
WHERE SO_ID = GET_SERVICE_CATEGORY_REC.SO_ID ;


END LOOP;

CLOSE GET_SERVICE_CATEGORY;
-------------------------------------------------

OPEN GET_SECTION_HANDLED_BY;

LOOP 

FETCH GET_SECTION_HANDLED_BY INTO GET_SECTION_HANDLED_BY_REC ;

EXIT WHEN GET_SECTION_HANDLED_BY%NOTFOUND;

UPDATE 
    CLARITY_ADMIN.PENDING_ETHERNET_DATA SET SECTION_HANDLED_BY  = GET_SECTION_HANDLED_BY_REC.SEOA_DEFAULTVALUE 
WHERE SO_ID = GET_SECTION_HANDLED_BY_REC.SO_ID ;


END LOOP;

CLOSE GET_SECTION_HANDLED_BY;

-------------------------------------------------

OPEN GET_ACCESS_MEDIUM;

LOOP 

FETCH GET_ACCESS_MEDIUM INTO GET_ACCESS_MEDIUM_REC ;

EXIT WHEN GET_ACCESS_MEDIUM%NOTFOUND;

UPDATE 
    CLARITY_ADMIN.PENDING_ETHERNET_DATA SET ACCESS_MEDIUM  = GET_ACCESS_MEDIUM_REC.SEOA_DEFAULTVALUE 
WHERE SO_ID = GET_ACCESS_MEDIUM_REC.SO_ID ;


END LOOP;

CLOSE GET_ACCESS_MEDIUM;

-------------------------------------------------

OPEN GET_SERVICE_SPEED;

LOOP 

FETCH GET_SERVICE_SPEED INTO GET_SERVICE_SPEED_REC ;

EXIT WHEN GET_SERVICE_SPEED%NOTFOUND;

UPDATE 
    CLARITY_ADMIN.PENDING_ETHERNET_DATA SET SERVICE_SPEED  = GET_SERVICE_SPEED_REC.SEOA_DEFAULTVALUE 
WHERE SO_ID = GET_SERVICE_SPEED_REC.SO_ID ;


END LOOP;

CLOSE GET_SERVICE_SPEED;

-------------------------------------------------

OPEN GET_ACCM_NAME;

LOOP 

FETCH GET_ACCM_NAME INTO GET_ACCM_NAME_REC ;

EXIT WHEN GET_ACCM_NAME%NOTFOUND;

UPDATE 
    CLARITY_ADMIN.PENDING_ETHERNET_DATA SET ACCMAN_NAME  = GET_ACCM_NAME_REC.ACCM_NAME 
WHERE SO_ID = GET_ACCM_NAME_REC.SO_ID ;


END LOOP;

CLOSE GET_ACCM_NAME;


COMMIT;

END PENDING_ENTERPRICE_DATA;

----Sasith 15-12-2013 -----Modified 19-12-2013
/
