CREATE OR REPLACE PROCEDURE CLARITY_ADMIN.PEND_RG_MDF_WO_DETAILS_DATA AS


CURSOR GET_BASE_DATA IS
             (SELECT
                AREA_AREA_CODE          "RTOM",
                WORO_AREA_CODE          "LEA", 
                WORO_SERO_ID            "SERVICE_ORDER", 
                WORO_ID                 "WORK_ORDER", 
                CIRT_DISPLAYNAME        "CCT_ID", 
                SERO_SERT_ABBREVIATION  "SERVICE_TYPE",
                (SELECT SEIT_ACTUAL_END_DATE FROM SERVICE_IMPLEMENTATION_TASKS
                 WHERE SEIT_TASKNAME = 'APPROVE SO'
                 AND SEIT_SERO_ID = SERO_ID) "APPROVED_DATE",
                WORO_WORG_NAME          "WORK_GROUP", 
                WORO_ORDT_TYPE          "ORDER_TYPE", 
                WORO_TASKNAME           "TASK_NAME",
                WORO_STAS_ABBREVIATION  "WO_STATUS", 
                WORO_USERUPDATED        "UPDATED_BY",
                TO_CHAR(SERO_DATECREATED,'DD/MM/YYYY HH24:MI:SS') "SO_CREATE_DATE",
                TO_CHAR(WORO_ASSIGNED_DATE,'DD/MM/YYYY HH24:MI:SS') "WO_ASSIGNED_DATE",
                ROUND(SYSDATE - WORO_ASSIGNED_DATE) "PENDING_WO_DELAY",        
                CUSR_NAME "CUSTOMER_NAME", 
                ((SELECT MAX (A.SEOA_DEFAULTVALUE) FROM SERVICE_ORDER_ATTRIBUTES A WHERE A.SEOA_SERO_ID = SERO_ID  AND SEOA_NAME = 'CUSTOMER CONTACT NO')||'/ '||
                (SELECT MAX (A.SEOA_DEFAULTVALUE) FROM SERVICE_ORDER_ATTRIBUTES A WHERE A.SEOA_SERO_ID = SERO_ID  AND SEOA_NAME = 'CUSTOMER_CONTACT_NUMBER')||'/ '||
                (SELECT MAX (A.SEOA_DEFAULTVALUE) FROM SERVICE_ORDER_ATTRIBUTES A WHERE A.SEOA_SERO_ID = SERO_ID  AND SEOA_NAME = 'IPTV_CONTACT_PHONE')) "CONTACT_NO",
                CUSR_CUTP_TYPE "CUS_TYPE",
                CUSR_ABBREVIATION "CR",
                (PORT_CARD_SLOT|| '-' ||PORT_NAME) "PORT",
                EQUP_LOCN_TTNAME "EQ_LOCATION",
                EQUP_EQUT_ABBREVIATION "EQ_TYPE",
                EQUP_INDEX "EQ_INDEX",
                EQUP_IPADDRESS "EQ_IP",
                EQUP_MANR_ABBREVIATION "EQ_MANUFACTURER",
                EQUP_EQUM_MODEL "EQ_MODEL",
                (ADDE_STREETNUMBER || ', ' || ADDE_STRN_NAMEANDTYPE || ', ' || ADDE_SUBURB || ', ' || ADDE_CITY || ', ' || ADDE_POSC_CODE) AS "ADDRESS",
                (SELECT WOOC_TEXT FROM WORK_ORDER_COMMENTS WC WHERE WOOC_WORO_ID = WORO_ID AND WC.WOOC_ID=(SELECT MAX(WOOC_ID)CID FROM WORK_ORDER_COMMENTS WHERE WOOC_WORO_ID=WC.WOOC_WORO_ID)) AS "COMMENTS"
                FROM WORK_ORDER, SERVICE_ORDERS, CIRCUITS, AREAS,PORT_LINKS, PORT_LINK_PORTS, PORTS, EQUIPMENT, SERVICES_ADDRESS, ADDRESSES, CUSTOMER, SERVICE_IMPLEMENTATION_TASKS, SERVICE_ORDER_ATTRIBUTES
                WHERE WORO_STAS_ABBREVIATION IN ('ASSIGNED','INPROGRESS')
                AND SEIT_STAS_ABBREVIATION = 'INPROGRESS'
                AND SEIT_ID = WORO_SEIT_ID
                AND CIRT_NAME = PORL_CIRT_NAME
                AND PORL_ID = POLP_PORL_ID
                AND POLP_FRAA_ID IS NULL
                AND POLP_PORT_ID = PORT_ID
                AND PORT_NAME NOT LIKE 'POTS-OUT-%'
                AND PORT_NAME NOT LIKE 'POTS-IN-%'
                AND EQUP_EQUT_ABBREVIATION IN ('MSAN-OG','MSAN-IG','MSAN-IW','MSAN-OP','MSAN-OW','DSLAM-HUAWEI','DSLAM-ZTE')
                AND PORT_EQUP_ID = EQUP_ID
                AND CIRT_SERV_ID = SADD_SERV_ID
                AND SADD_ADDE_ID = ADDE_ID
                AND SADD_TYPE = 'BEND'
                AND CIRT_CUSR_ABBREVIATION = CUSR_ABBREVIATION
                AND WORO_SERO_ID = SEOA_SERO_ID
                AND SEOA_NAME = 'CUSTOMER CONTACT NO'
                AND WORO_AREA_CODE = AREA_CODE
                AND WORO_SERO_ID = SERO_ID
                AND WORO_CIRT_NAME = CIRT_NAME
                AND WORO_WORG_NAME IN ('WT-JL-OSP-NC',
                                       'WT-WT-OSP-NC',
                                       'WT-RG-OSP-NC',
                                       'MD-MD-OSP-NC',
                                       'WT-RG-SW-RG',
                                       'WT-WT-SW-WT',
                                       'WT-RG-SW-RG',
                                       'WT-JL-SW-JL',
                                       'WT-JL-SW-JLA',
                                       'WT-WT-SW-WTC',
                                       'WT-JL-SW-JLW'))
                     UNION
                (SELECT
                AREA_AREA_CODE          "RTOM",
                WORO_AREA_CODE          "LEA", 
                WORO_SERO_ID            "SERVICE_ORDER", 
                WORO_ID                 "WORK_ORDER", 
                CIRT_DISPLAYNAME        "CCT_ID", 
                SERO_SERT_ABBREVIATION  "SERVICE_TYPE",
                (SELECT SEIT_ACTUAL_END_DATE FROM SERVICE_IMPLEMENTATION_TASKS
                 WHERE SEIT_TASKNAME = 'APPROVE SO'
                 AND SEIT_SERO_ID = SERO_ID) "APPROVED_DATE",
                WORO_WORG_NAME          "WORK_GROUP", 
                WORO_ORDT_TYPE          "ORDER_TYPE", 
                WORO_TASKNAME           "TASK_NAME",
                WORO_STAS_ABBREVIATION  "WO_STATUS", 
                WORO_USERUPDATED        "UPDATED_BY",
                TO_CHAR(SERO_DATECREATED,'DD/MM/YYYY HH24:MI:SS') "SO_CREATE_DATE",
                TO_CHAR(WORO_ASSIGNED_DATE,'DD/MM/YYYY HH24:MI:SS') "WO_ASSIGNED_DATE",
                ROUND(SYSDATE - WORO_ASSIGNED_DATE) "PENDING_WO_DELAY",        
                CUSR_NAME "CUSTOMER_NAME", 
                ((SELECT MAX (A.SEOA_DEFAULTVALUE) FROM SERVICE_ORDER_ATTRIBUTES A WHERE A.SEOA_SERO_ID = SERO_ID  AND SEOA_NAME = 'CUSTOMER CONTACT NO')||'/ '||
                (SELECT MAX (A.SEOA_DEFAULTVALUE) FROM SERVICE_ORDER_ATTRIBUTES A WHERE A.SEOA_SERO_ID = SERO_ID  AND SEOA_NAME = 'CUSTOMER_CONTACT_NUMBER')||'/ '||
                (SELECT MAX (A.SEOA_DEFAULTVALUE) FROM SERVICE_ORDER_ATTRIBUTES A WHERE A.SEOA_SERO_ID = SERO_ID  AND SEOA_NAME = 'IPTV_CONTACT_PHONE')) "CONTACT_NO",
                CUSR_CUTP_TYPE "CUS_TYPE",
                CUSR_ABBREVIATION "CR",
                (PORT_CARD_SLOT|| '-' ||PORT_NAME) "PORT",
                EQUP_LOCN_TTNAME "EQ_LOCATION",
                EQUP_EQUT_ABBREVIATION "EQ_TYPE",
                EQUP_INDEX "EQ_INDEX",
                EQUP_IPADDRESS "EQ_IP",
                EQUP_MANR_ABBREVIATION "EQ_MANUFACTURER",
                EQUP_EQUM_MODEL "EQ_MODEL",
                (ADDE_STREETNUMBER || ', ' || ADDE_STRN_NAMEANDTYPE || ', ' || ADDE_SUBURB || ', ' || ADDE_CITY || ', ' || ADDE_POSC_CODE) AS "ADDRESS",
                (SELECT WOOC_TEXT FROM WORK_ORDER_COMMENTS WC WHERE WOOC_WORO_ID = WORO_ID AND WC.WOOC_ID=(SELECT MAX(WOOC_ID)CID FROM WORK_ORDER_COMMENTS WHERE WOOC_WORO_ID=WC.WOOC_WORO_ID)) AS "COMMENTS"
                FROM WORK_ORDER, SERVICE_ORDERS, CIRCUITS, AREAS,PORT_LINKS, PORT_LINK_PORTS, PORTS, EQUIPMENT, SERVICES_ADDRESS, ADDRESSES, CUSTOMER, SERVICE_IMPLEMENTATION_TASKS, SERVICE_ORDER_ATTRIBUTES
                WHERE WORO_STAS_ABBREVIATION IN ('ASSIGNED','INPROGRESS')
                AND SEIT_STAS_ABBREVIATION = 'INPROGRESS'
                AND SEIT_ID = WORO_SEIT_ID
                AND CIRT_NAME = PORL_CIRT_NAME
                AND PORL_ID = POLP_PORL_ID
                AND POLP_FRAA_ID IS NULL
                AND POLP_PORT_ID = PORT_ID
                AND PORT_NAME NOT LIKE 'POTS-OUT-%'
                AND PORT_NAME NOT LIKE 'POTS-IN-%'
                AND EQUP_EQUT_ABBREVIATION IN ('MSAN-OG','MSAN-IG','MSAN-IW','MSAN-OP','MSAN-OW','DSLAM-HUAWEI','DSLAM-ZTE')
                AND PORT_EQUP_ID = EQUP_ID
                AND CIRT_SERV_ID = SADD_SERV_ID
                AND SADD_ADDE_ID = ADDE_ID
                AND SADD_TYPE = 'BEND'
                AND CIRT_CUSR_ABBREVIATION = CUSR_ABBREVIATION
                AND WORO_SERO_ID = SEOA_SERO_ID
                AND SEOA_NAME = 'CUSTOMER CONTACT NO'
                AND WORO_AREA_CODE = AREA_CODE
                AND WORO_SERO_ID = SERO_ID
                AND WORO_CIRT_NAME = CIRT_NAME
                AND WORO_WORG_NAME IN ('WT-JL-OSP-NC',
                                       'WT-WT-OSP-NC',
                                       'WT-RG-OSP-NC',
                                       'MD-MD-OSP-NC',
                                       'WT-RG-SW-RG',
                                       'WT-WT-SW-WT',
                                       'WT-RG-SW-RG',
                                       'WT-JL-SW-JL',
                                       'WT-JL-SW-JLA',
                                       'WT-WT-SW-WTC',
                                       'WT-JL-SW-JLW'));


GET_BASE_DATA_REC             GET_BASE_DATA%ROWTYPE;

BEGIN

DELETE FROM CLARITY_ADMIN.PENDINGE_RG_MDF_WO_DETAILS;

OPEN GET_BASE_DATA;

LOOP 

FETCH GET_BASE_DATA INTO GET_BASE_DATA_REC ;

EXIT WHEN GET_BASE_DATA%NOTFOUND;

INSERT INTO CLARITY_ADMIN.PENDINGE_RG_MDF_WO_DETAILS
(
RTOM,
LEA,
SERVICE_ORDER,
WORK_ORDER,
CCT_ID,
SERVICE_TYPE,
APPROVED_DATE,
WORK_GROUP,
ORDER_TYPE,
TASK_NAME,
WO_STATUS,
UPDATED_BY,
SO_CREATE_DATE,
WO_ASSIGNED_DATE,
PENDING_WO_DELAY,
CUSTOMER_NAME,
CONTACT_NO,
CUS_TYPE,
CR,
PORT,
EQ_LOCATION,
EQ_TYPE,
EQ_INDEX,
EQ_IP,
EQ_MANUFACTURER,
EQ_MODEL,
ADDRESS,
COMMENTS
)
VALUES
(
GET_BASE_DATA_REC.RTOM,
GET_BASE_DATA_REC.LEA,
GET_BASE_DATA_REC.SERVICE_ORDER,
GET_BASE_DATA_REC.WORK_ORDER,
GET_BASE_DATA_REC.CCT_ID,
GET_BASE_DATA_REC.SERVICE_TYPE,
GET_BASE_DATA_REC.APPROVED_DATE,
GET_BASE_DATA_REC.WORK_GROUP,
GET_BASE_DATA_REC.ORDER_TYPE,
GET_BASE_DATA_REC.TASK_NAME,
GET_BASE_DATA_REC.WO_STATUS,
GET_BASE_DATA_REC.UPDATED_BY,
GET_BASE_DATA_REC.SO_CREATE_DATE,
GET_BASE_DATA_REC.WO_ASSIGNED_DATE,
GET_BASE_DATA_REC.PENDING_WO_DELAY,
GET_BASE_DATA_REC.CUSTOMER_NAME,
GET_BASE_DATA_REC.CONTACT_NO,
GET_BASE_DATA_REC.CUS_TYPE,
GET_BASE_DATA_REC.CR,
GET_BASE_DATA_REC.PORT,
GET_BASE_DATA_REC.EQ_LOCATION,
GET_BASE_DATA_REC.EQ_TYPE,
GET_BASE_DATA_REC.EQ_INDEX,
GET_BASE_DATA_REC.EQ_IP,
GET_BASE_DATA_REC.EQ_MANUFACTURER,
GET_BASE_DATA_REC.EQ_MODEL,
GET_BASE_DATA_REC.ADDRESS,
GET_BASE_DATA_REC.COMMENTS
);

END LOOP;

CLOSE GET_BASE_DATA;

COMMIT;

END PEND_RG_MDF_WO_DETAILS_DATA;

---- Dinesh Perera 23-10-2014 -----
/
