CREATE OR REPLACE PROCEDURE CLARITY_ADMIN.PRE_CUTOVER_ERROR_TASKS_DATA AS


CURSOR GET_BASE_DATA IS
        SELECT  
        (select AREA_AREA_CODE from areas where AREA_CODE=So.SERO_AREA_CODE) AS "RTOM",  
        SERO_ID,
        SERO_ORDT_TYPE,
        SERO_SERT_ABBREVIATION,
        SERO_ACCT_NUMBER,
        SERO_CUSR_ABBREVIATION,
        SERO_SERV_ID,
        (select cirt_displayname from circuits where cirt_name = so.SERO_CIRT_NAME) AS "CCT_NAME",
        SEIT_ID,
        SEIT_TASKNAME,
        SEIT_STAS_ABBREVIATION,
        SEOA_DEFAULTVALUE DSP_DATE,
        SERO_DATECREATED,
        SERO_STAS_ABBREVIATION,
        (SELECT SETC_TEXT FROM SERVICE_TASK_COMMENTS SC WHERE SI.SEIT_ID=SETC_SEIT_ID AND SC.SETC_ID=(SELECT MAX(SETC_ID)CID
         FROM SERVICE_TASK_COMMENTS
         WHERE SETC_SEIT_ID=SC.SETC_SEIT_ID)) AS "COMM"
         
        FROM    SERVICE_ORDERS SO,SERVICE_IMPLEMENTATION_TASKS SI,SERVICE_ORDER_ATTRIBUTES SA
        WHERE   SERO_ID=SEIT_SERO_ID
        AND     SEOA_SERO_ID=SEIT_SERO_ID
        AND     SEOA_NAME='ACTUAL_DSP_DATE'
        AND     TO_CHAR(SERO_DATECREATED,'YYYYMMDD')<'20121026'
        AND     SERO_STAS_ABBREVIATION NOT IN ('CANCELLED','CLOSED')
        AND     SEIT_STAS_ABBREVIATION = 'ERROR'
        AND NOT EXISTS (SELECT 'X'
        FROM    WORK_ORDER
        WHERE   WORO_SERO_ID=SO.SERO_ID
        AND     WORO_STAS_ABBREVIATION IN ('INPROGRESS','ASSIGNED'));


GET_BASE_DATA_REC             GET_BASE_DATA%ROWTYPE;

BEGIN

DELETE FROM CLARITY_ADMIN.PRE_CUTOVER_ERROR_TASKS WHERE SERO_ID IS NOT NULL;

OPEN GET_BASE_DATA;

LOOP 

FETCH GET_BASE_DATA INTO GET_BASE_DATA_REC ;

EXIT WHEN GET_BASE_DATA%NOTFOUND;

INSERT INTO CLARITY_ADMIN.PRE_CUTOVER_ERROR_TASKS
(
RTOM,
SERO_ID,
SERO_ORDT_TYPE,
SERO_SERT_ABBREVIATION,
SERO_ACCT_NUMBER,
SERO_CUSR_ABBREVIATION,
SERO_SERV_ID,
CCT_NAME,
SEIT_ID,
SEIT_TASKNAME,
SEIT_STAS_ABBREVIATION,
DSP_DATE,
SERO_DATECREATED,
SERO_STAS_ABBREVIATION,
COMM
)
VALUES
(
GET_BASE_DATA_REC.RTOM,
GET_BASE_DATA_REC.SERO_ID,
GET_BASE_DATA_REC.SERO_ORDT_TYPE,
GET_BASE_DATA_REC.SERO_SERT_ABBREVIATION,
GET_BASE_DATA_REC.SERO_ACCT_NUMBER,
GET_BASE_DATA_REC.SERO_CUSR_ABBREVIATION,
GET_BASE_DATA_REC.SERO_SERV_ID,
GET_BASE_DATA_REC.CCT_NAME,
GET_BASE_DATA_REC.SEIT_ID,
GET_BASE_DATA_REC.SEIT_TASKNAME,
GET_BASE_DATA_REC.SEIT_STAS_ABBREVIATION,
GET_BASE_DATA_REC.DSP_DATE,
GET_BASE_DATA_REC.SERO_DATECREATED,
GET_BASE_DATA_REC.SERO_STAS_ABBREVIATION,
GET_BASE_DATA_REC.COMM
);

END LOOP;

CLOSE GET_BASE_DATA;

COMMIT;

END PRE_CUTOVER_ERROR_TASKS_DATA;

---- Dinesh Perera 02-12-2013 -----
/
