CREATE OR REPLACE PROCEDURE CLARITY_ADMIN.SO_REPORT_DATA ( STD_DATE IN  DATE , END_DATE IN  DATE ) IS

ST_DATE   DATE := STD_DATE ;
ED_DATE   DATE := END_DATE ;

CURSOR GET_SO_DATA IS 

SELECT 
SO.SERO_ID,
SO.SERO_AREA_CODE,
SO.SERO_SERT_ABBREVIATION,
SO.SERO_ORDT_TYPE,
SO.SERO_DATECREATED,
SO.SERO_STATUSDATE,
SO.SERO_ACCT_NUMBER,
SO.SERO_CUSR_ABBREVIATION,
SO.SERO_OEID
FROM 
SERVICE_ORDERS SO
WHERE 
    SO.SERO_STAS_ABBREVIATION = 'CLOSED'
AND SO.SERO_STATUSDATE BETWEEN ST_DATE AND END_DATE ;

CURSOR GET_CIRT_NAME IS
SELECT 
SO_ID,
CIRT_DISPLAYNAME
FROM 
CLARITY_ADMIN.SO_INFO_REPORT,
CIRCUITS, SERVICE_ORDERS
WHERE 
    SO_ID  = SERO_ID
AND SERO_CIRT_NAME   = CIRT_NAME(+) ;

CURSOR GET_ACTUAL_DSP_DATE IS
SELECT 
SO_ID,
SEOA_DEFAULTVALUE
FROM 
CLARITY_ADMIN.SO_INFO_REPORT,
SERVICE_ORDER_ATTRIBUTES
WHERE 
    SO_ID  = SEOA_SERO_ID(+)
AND SEOA_NAME   ='ACTUAL_DSP_DATE' ;

CURSOR GET_SA_SO_INITIATOR  IS
SELECT 
SO_ID,
SEOA_DEFAULTVALUE
FROM 
CLARITY_ADMIN.SO_INFO_REPORT,
SERVICE_ORDER_ATTRIBUTES
WHERE 
    SO_ID  = SEOA_SERO_ID(+)
AND SEOA_NAME   ='SA_SO_INITIATOR' ;

CURSOR GET_SA_PACKAGE_NAME  IS
SELECT 
SO_ID,
SEOA_DEFAULTVALUE
FROM 
CLARITY_ADMIN.SO_INFO_REPORT,
SERVICE_ORDER_ATTRIBUTES
WHERE 
    SO_ID  = SEOA_SERO_ID(+)
AND SEOA_NAME   ='SA_PACKAGE_NAME' ;

CURSOR GET_IPTV_PACKAGE  IS
SELECT 
SO_ID,
SEOA_DEFAULTVALUE
FROM 
CLARITY_ADMIN.SO_INFO_REPORT,
SERVICE_ORDER_ATTRIBUTES
WHERE 
    SO_ID  = SEOA_SERO_ID(+)
AND SEOA_NAME   ='IPTV_PACKAGE' ;

CURSOR GET_IPTV_OFE  IS
SELECT
DISTINCT SO_ID,
SOFE_DEFAULTVALUE,
SOFE_PREV_VALUE
FROM
CLARITY_ADMIN.SO_INFO_REPORT,
SERVICE_ORDER_FEATURES
WHERE
SO_ID = SOFE_SERO_ID(+)
AND SOFE_FEATURE_NAME = 'IPTV';

CURSOR GET_INTERNET_OFE  IS
SELECT
DISTINCT SO_ID,
SOFE_DEFAULTVALUE,
SOFE_PREV_VALUE
FROM
CLARITY_ADMIN.SO_INFO_REPORT,
SERVICE_ORDER_FEATURES
WHERE
SO_ID = SOFE_SERO_ID(+)
AND SOFE_FEATURE_NAME = 'INTERNET';


CURSOR GET_APPROVE_SO_D  IS
SELECT
SO_ID,
SEIT_ACTUAL_END_DATE
FROM
CLARITY_ADMIN.SO_INFO_REPORT,
SERVICE_IMPLEMENTATION_TASKS
WHERE SO_ID                 = SEIT_SERO_ID(+)
AND SEIT_STAS_ABBREVIATION  ='COMPLETED'
AND SEIT_TASKNAME           = 'APPROVE SO';

CURSOR GET_MILESTONE_ONE_D  IS
SELECT
SO_ID,
SEIT_ACTUAL_END_DATE
FROM
CLARITY_ADMIN.SO_INFO_REPORT,
SERVICE_IMPLEMENTATION_TASKS
WHERE SO_ID                 = SEIT_SERO_ID(+)
AND SEIT_STAS_ABBREVIATION  ='COMPLETED'
AND SEIT_TASKNAME           = 'MILESTONE 1';



GET_SO_DATA_REC             GET_SO_DATA%ROWTYPE;
GET_CIRT_NAME_REC           GET_CIRT_NAME%ROWTYPE;
GET_ACTUAL_DSP_DATE_REC     GET_ACTUAL_DSP_DATE%ROWTYPE;
GET_SA_SO_INITIATOR_REC     GET_SA_SO_INITIATOR%ROWTYPE;
GET_SA_PACKAGE_NAME_REC     GET_SA_PACKAGE_NAME%ROWTYPE;
GET_IPTV_PACKAGE_REC        GET_IPTV_PACKAGE%ROWTYPE;
GET_IPTV_OFE_REC            GET_IPTV_OFE%ROWTYPE;
GET_INTERNET_OFE_REC        GET_INTERNET_OFE%ROWTYPE;
GET_APPROVE_SO_D_REC        GET_APPROVE_SO_D%ROWTYPE;
GET_MILESTONE_ONE_D_REC     GET_MILESTONE_ONE_D%ROWTYPE;


BEGIN

DELETE FROM CLARITY_ADMIN.SO_INFO_REPORT WHERE SO_ID IS NOT NULL;

INSERT INTO 
CLARITY_ADMIN.SO_INFO_REPORT_LOG 
(
SOI_ID,
SOI_EMO_ID,
LOG_DESC,
CHANGE_DATE
) 
VALUES
(
SO_INFO_SEQ.NEXTVAL,
(SELECT USER FROM DUAL),
'RECORD-DELETED SUCCESSFULLY',
(SELECT SYSDATE FROM DUAL)
) ;

-------------------------------------------------

OPEN GET_SO_DATA;

LOOP 

FETCH GET_SO_DATA INTO GET_SO_DATA_REC ;

EXIT WHEN GET_SO_DATA%NOTFOUND;

INSERT INTO CLARITY_ADMIN.SO_INFO_REPORT
(
SO_ID,
SO_LEA,
SO_SERVICE_TYPE,
SO_ORDER_TYPE,
SO_DATECREATED,
SO_CLOSE_DATE,
SO_ACCT_NUMBER,
SO_CUSR_ABBREVIATION,
SO_OEID
)
VALUES
(
GET_SO_DATA_REC.SERO_ID,
GET_SO_DATA_REC.SERO_AREA_CODE,
GET_SO_DATA_REC.SERO_SERT_ABBREVIATION,
GET_SO_DATA_REC.SERO_ORDT_TYPE,
GET_SO_DATA_REC.SERO_DATECREATED,
GET_SO_DATA_REC.SERO_STATUSDATE,
GET_SO_DATA_REC.SERO_ACCT_NUMBER,
GET_SO_DATA_REC.SERO_CUSR_ABBREVIATION,
GET_SO_DATA_REC.SERO_OEID
); 

END LOOP;

CLOSE GET_SO_DATA;

COMMIT;
-------------------------------------------------

OPEN GET_CIRT_NAME;

LOOP 

FETCH GET_CIRT_NAME INTO GET_CIRT_NAME_REC ;

EXIT WHEN GET_CIRT_NAME%NOTFOUND;

UPDATE 
    CLARITY_ADMIN.SO_INFO_REPORT SET SO_CIRT_NAME = GET_CIRT_NAME_REC.CIRT_DISPLAYNAME 
WHERE SO_ID = GET_CIRT_NAME_REC.SO_ID ;


END LOOP;

CLOSE GET_CIRT_NAME;

-------------------------------------------------
OPEN GET_ACTUAL_DSP_DATE;

LOOP 

FETCH GET_ACTUAL_DSP_DATE INTO GET_ACTUAL_DSP_DATE_REC ;

EXIT WHEN GET_ACTUAL_DSP_DATE%NOTFOUND;

UPDATE 
    CLARITY_ADMIN.SO_INFO_REPORT SET SO_DSP_DATE = GET_ACTUAL_DSP_DATE_REC.SEOA_DEFAULTVALUE 
WHERE SO_ID = GET_ACTUAL_DSP_DATE_REC.SO_ID ;


END LOOP;

CLOSE GET_ACTUAL_DSP_DATE;

-------------------------------------------------

OPEN GET_SA_SO_INITIATOR;

LOOP 

FETCH GET_SA_SO_INITIATOR INTO GET_SA_SO_INITIATOR_REC ;

EXIT WHEN GET_SA_SO_INITIATOR%NOTFOUND;

UPDATE 
    CLARITY_ADMIN.SO_INFO_REPORT SET SO_INITIATOR = GET_SA_SO_INITIATOR_REC.SEOA_DEFAULTVALUE 
WHERE SO_ID = GET_SA_SO_INITIATOR_REC.SO_ID ;


END LOOP;

CLOSE GET_SA_SO_INITIATOR;
-------------------------------------------------
OPEN GET_SA_PACKAGE_NAME;

LOOP 

FETCH GET_SA_PACKAGE_NAME INTO GET_SA_PACKAGE_NAME_REC ;

EXIT WHEN GET_SA_PACKAGE_NAME%NOTFOUND;

UPDATE 
    CLARITY_ADMIN.SO_INFO_REPORT SET SO_ADSL_Package = GET_SA_PACKAGE_NAME_REC.SEOA_DEFAULTVALUE 
WHERE SO_ID = GET_SA_PACKAGE_NAME_REC.SO_ID ;


END LOOP;

CLOSE GET_SA_PACKAGE_NAME;

-------------------------------------------------
OPEN GET_IPTV_PACKAGE;

LOOP 

FETCH GET_IPTV_PACKAGE INTO GET_IPTV_PACKAGE_REC ;

EXIT WHEN GET_IPTV_PACKAGE%NOTFOUND;

UPDATE 
    CLARITY_ADMIN.SO_INFO_REPORT SET SO_IPTV_Package  = GET_IPTV_PACKAGE_REC.SEOA_DEFAULTVALUE 
WHERE SO_ID = GET_IPTV_PACKAGE_REC.SO_ID ;


END LOOP;

CLOSE GET_IPTV_PACKAGE;
-------------------------------------------------
OPEN GET_IPTV_OFE;

LOOP 

FETCH GET_IPTV_OFE INTO GET_IPTV_OFE_REC ;

EXIT WHEN GET_IPTV_OFE%NOTFOUND;

UPDATE 
    CLARITY_ADMIN.SO_INFO_REPORT SET SO_CURR_IPTV   = GET_IPTV_OFE_REC.SOFE_DEFAULTVALUE,
    SO_PREV_IPTV   = GET_IPTV_OFE_REC.SOFE_PREV_VALUE      
WHERE SO_ID = GET_IPTV_OFE_REC.SO_ID ;


END LOOP;

CLOSE GET_IPTV_OFE;
-------------------------------------------------
OPEN GET_INTERNET_OFE;

LOOP 

FETCH GET_INTERNET_OFE INTO GET_INTERNET_OFE_REC ;

EXIT WHEN GET_INTERNET_OFE%NOTFOUND;

UPDATE 
    CLARITY_ADMIN.SO_INFO_REPORT  SET SO_CURR_INTERNET   = GET_INTERNET_OFE_REC.SOFE_DEFAULTVALUE,
    SO_PREV_INTERNET   = GET_INTERNET_OFE_REC.SOFE_PREV_VALUE      
WHERE SO_ID = GET_INTERNET_OFE_REC.SO_ID ;


END LOOP;

CLOSE GET_INTERNET_OFE;
-------------------------------------------------

OPEN GET_APPROVE_SO_D;

LOOP 

FETCH GET_APPROVE_SO_D INTO GET_APPROVE_SO_D_REC ;

EXIT WHEN GET_APPROVE_SO_D%NOTFOUND;

UPDATE 
    CLARITY_ADMIN.SO_INFO_REPORT  SET SO_Approved_Date   = GET_APPROVE_SO_D_REC.SEIT_ACTUAL_END_DATE
WHERE SO_ID = GET_APPROVE_SO_D_REC.SO_ID ;


END LOOP;

CLOSE GET_APPROVE_SO_D;
-------------------------------------------------

OPEN GET_MILESTONE_ONE_D;

LOOP 

FETCH GET_MILESTONE_ONE_D INTO GET_MILESTONE_ONE_D_REC ;

EXIT WHEN GET_MILESTONE_ONE_D%NOTFOUND;

UPDATE 
    CLARITY_ADMIN.SO_INFO_REPORT  SET SO_MILESTONE_1_ACTUAL_END_DATE   = GET_MILESTONE_ONE_D_REC.SEIT_ACTUAL_END_DATE
WHERE SO_ID = GET_MILESTONE_ONE_D_REC.SO_ID ;


END LOOP;

CLOSE GET_MILESTONE_ONE_D;
-------------------------------------------------
INSERT INTO 
CLARITY_ADMIN.SO_INFO_REPORT_LOG 
(
SOI_ID,
SOI_EMO_ID,
LOG_DESC,
CHANGE_DATE
) 
VALUES
(
SO_INFO_SEQ.NEXTVAL,
(SELECT USER FROM DUAL),
'RECORD-INSERTED SUCCESSFULLY',
(SELECT SYSDATE FROM DUAL)
) ;
COMMIT;

END SO_REPORT_DATA;

---- Dinesh Perera 23-11-2013 -----
/
